# Generated by Django 5.0.3 on 2024-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transaction_pin',
            field=models.BigIntegerField(),
        ),
    ]
