# Generated by Django 5.0.3 on 2024-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
