# Generated by Django 5.0.3 on 2024-06-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitysettings',
            name='disco_name',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
