# Generated by Django 5.0.3 on 2024-06-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_electricitysettings_disco_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitysettings',
            name='disco_name',
        ),
    ]
